# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alreadyRunningWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_alreadyRunningWindow(object):
    def __init__(self):
        self.gridLayout = None
        self.buttonBox = None
        self.label = None

    def setupUi(self, alreadyRunningWindow):
        alreadyRunningWindow.setObjectName("alreadyRunningWindow")
        alreadyRunningWindow.resize(310, 98)
        alreadyRunningWindow.setMinimumSize(QtCore.QSize(310, 98))
        alreadyRunningWindow.setMaximumSize(QtCore.QSize(310, 98))
        alreadyRunningWindow.setWindowTitle("Error")
        alreadyRunningWindow.setWhatsThis("")
        self.gridLayout = QtWidgets.QGridLayout(alreadyRunningWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(alreadyRunningWindow)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(alreadyRunningWindow)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)

        self.retranslateUi(alreadyRunningWindow)
        self.buttonBox.rejected.connect(alreadyRunningWindow.reject)  # type: ignore
        self.buttonBox.accepted.connect(alreadyRunningWindow.accept)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(alreadyRunningWindow)

    def retranslateUi(self, alreadyRunningWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("alreadyRunningWindow", "WARP-Linux already running!"))
